stages:
  - test
  - semrel
  - dockerrelease

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  NPM_TOKEN: ${CI_JOB_TOKEN}

test:
  image: node:22
  stage: test
  before_script:
    - cd server/calserv
    - npm i -f
  script:
    - npm test

build:
  image: node:22
  stage: test
  before_script:
    - cd server/calserv
    - npm i -f
    - cp -r deployment_example/config ./config
  script:
    - npm run build


semrel:
  image: node:22
  stage: semrel
  before_script:
    - cd server/calserv
    - npm i -f
  script:
    - npx semantic-release
  only:
    - production

docker:
  stage: dockerrelease
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - cd server/calserv
    - docker build -t $CI_REGISTRY/i5/infrastructure/room-occupancy/calserv:$CI_COMMIT_TAG -t $CI_REGISTRY/i5/infrastructure/room-occupancy/calserv:latest .
    - docker push $CI_REGISTRY/i5/infrastructure/room-occupancy/calserv --all-tags
  only:
    - tags
