build:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - cd server/calserv
    - docker build -t $CI_REGISTRY/i5/infrastructure/room-occupancy/calserv:latest .
    - docker push $CI_REGISTRY/i5/infrastructure/room-occupancy/calserv:latest
variables:
  DOCKER_TLS_CERTDIR: "/certs"