services:
  calserv:
    image: registry.git.rwth-aachen.de/i5/infrastructure/room-occupancy/calserv
    ports:
      - 3001:3001
    env_file: "../calserv/.env"
#    environment:
#      - EXC_USER=test@test.de
#      - EXC_PASS=password
    volumes:
      - ./config:/home/node/app/config
