services:
  room-manager:
    image: registry.git.rwth-aachen.de/i5/infrastructure/room-mate/room-manager
    restart: always
    ports:
      - 3001:3001
    env_file: "../.env"
    environment:
#      - SECRET=password
      - STORAGE=FILE

    volumes:
      - ./calendars.json:/home/node/app/config/calendars.json
      - ./logs:/home/node/app/logs
