name: Nightly

on:
  push:
    branches: [development]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  image:
    needs: ci
    uses: ./.github/workflows/docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      tags: nightly
